### PR TITLE
Hardcode in checks for block version and block 0 or 1

### PR DESCRIPTION
**Pull request by alexlyp**
If version = 0 then use testnet params, and the same for version = 1 for mainnet.

Also check for blocks 0 and 1.  Block 0 should show no reward and block 1 should show the total premine value (100000 for testnet, 1680000 for mainnet)

### CODE REVIEW

**Comment by cjepson** [comment]
ntACK, bit of a hack but should work fine for explorer purposes.

**Comment by alexlyp** [comment]
Yah agree about the hack.  I plan on adding a true params area to avoid the magic numbers.  Will most likely begin on that PR next week.

**Comment by jcvernaleo** [comment]
Looks good to me.  OK after you squash and give one combined commit message.

**Comment by jcvernaleo** [comment]
OK

**Pull request merged**
